import { CodeMaker } from "codemaker";
import { Assembly, ModuleLike } from "jsii-reflect";

export abstract class RustModule {
  public readonly moduleName: string;
  
  private readonly subCrates: RustSubmodule[] = [];

  constructor(jsiiModule: ModuleLike) {
    this.moduleName = jsiiModule.fqn.replace(/\./g, '/');

    this.subCrates = jsiiModule.submodules.map(
      (submodule) => {
        // Change . to / in fqn to match Rust crate structure
        return new RustSubmodule(submodule);
      }
    );
  }

  public emit(code: CodeMaker): void {
    this.emitSubCrates(code);
  }

  private emitSubCrates(code: CodeMaker): void {
    for (const subCrate of this.subCrates) {
      subCrate.emit(code);
    }
  }
}

export class Crate extends RustModule {
  private readonly assembly: Assembly;

  constructor(assembly: Assembly) {
    // Consider following:
    // this.crateName = assembly.name.replace(/[^a-zA-Z0-9_]/g, "-");
    super(assembly);
    this.assembly = assembly;
  }

  public emit(code: CodeMaker): void {
    super.emit(code);

    this.emitToml(code);
    this.emitLib(code);
  }

  private emitToml(code: CodeMaker): void {
    code.openFile(`${this.moduleName}/Cargo.toml`);
    code.line(`[package]`);
    code.line(`name = "${this.moduleName}"`);
    code.line(`version = "${this.assembly.version}"`);
    code.line(`edition = "2024"`);
    code.closeFile(`${this.moduleName}/Cargo.toml`);
  }

  private emitLib(code: CodeMaker): void {
    code.openFile(`${this.moduleName}/src/lib.rs`);
    code.line(`// This file is auto-generated by jsii-pacmak.`);
    code.line(`// Do not edit this file manually.`);
    code.closeFile(`${this.moduleName}/src/lib.rs`);
  }
}

export class RustSubmodule extends RustModule {
  // public emit(code: CodeMaker): void {
  //   super.emit(code);
  //   // code.openFile(`${this.crateName}/src/${this.crateName}.rs`);
  //   // code.line(`// This file is auto-generated by jsii-pacmak.`);
  //   // code.line(`// Do not edit this file manually.`);
  //   // code.closeFile(`${this.crateName}/src/${this.crateName}.rs`);
  // }

  public emit(code: CodeMaker): void {
    super.emit(code);

    code.openFile(`${this.moduleName}.rs`);
    code.line(`// This file is auto-generated by jsii-pacmak.`);
    code.line(`// Do not edit this file manually.`);
    code.closeFile(`${this.moduleName}.rs`);
  }
}