import { CodeMaker } from "codemaker";
import { Assembly, ModuleLike } from "jsii-reflect";

export abstract class RustModule {
  public readonly moduleName: string;

  protected readonly subCrates: RustSubmodule[] = [];

  constructor(jsiiModule: ModuleLike, modulePath?: string) {
    // Change . to / in fqn to match Rust crate structure
    this.moduleName = jsiiModule.fqn.replace(/\./g, '/');

    this.subCrates = jsiiModule.submodules.map(
      (submodule) => {
        return new RustSubmodule(submodule, modulePath);
      }
    );
  }

  public emit(code: CodeMaker): void {
    this.emitSubCrates(code);
  }

  private emitSubCrates(code: CodeMaker): void {
    for (const subCrate of this.subCrates) {
      subCrate.emit(code);
    }
  }
}

export class Crate extends RustModule {
  private readonly assembly: Assembly;

  constructor(assembly: Assembly) {
    super(assembly, `${assembly.name}/src`);
    this.assembly = assembly;
  }

  public emit(code: CodeMaker): void {
    super.emit(code);

    this.emitToml(code);
    this.emitLib(code);
  }

  private emitToml(code: CodeMaker): void {
    code.openFile(`${this.moduleName}/Cargo.toml`);
    code.line(`[package]`);
    code.line(`name = "${this.moduleName}"`);
    code.line(`version = "${this.assembly.version}"`);
    code.line(`edition = "2024"`);
    code.closeFile(`${this.moduleName}/Cargo.toml`);
  }

  private emitLib(code: CodeMaker): void {
    code.openFile(`${this.moduleName}/src/lib.rs`);
    code.line(`// This file is auto-generated by jsii-pacmak.`);
    code.line(`// Do not edit this file manually.`);

    for (const subCrate of this.subCrates) {
      code.line(`#[cfg(feature = "${subCrate.moduleName}")]`);
      code.line(`pub mod ${subCrate.moduleName};`);
    }

    code.closeFile(`${this.moduleName}/src/lib.rs`);
  }
}

export class RustSubmodule extends RustModule {
  private readonly submodulePath: string;

  constructor(submodule: ModuleLike, modulePath?: string) {
    super(submodule, modulePath);
    this.submodulePath = modulePath ?? this.moduleName;
  }

  public emit(code: CodeMaker): void {
    super.emit(code);

    code.openFile(`${this.submodulePath}/${this.moduleName}.rs`);
    code.line(`// This file is auto-generated by jsii-pacmak.`);
    code.line(`// Do not edit this file manually.`);
    code.closeFile(`${this.submodulePath}/${this.moduleName}.rs`);
  }
}