import { CodeMaker } from "codemaker";
import { Assembly, ModuleLike } from "jsii-reflect";

export abstract class RustModule {
  public readonly moduleName: string;

  protected readonly subCrates: RustSubmodule[] = [];

  constructor(jsiiModule: ModuleLike, modulesPath?: string) {
    // make snake case from FQN
    let moduleName = jsiiModule.fqn.split('.').pop()!.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();

    moduleName = moduleName.replace(/[@/]/g, '-');
    moduleName = moduleName.replace(/^[^a-zA-Z]+/, '');

    this.moduleName = moduleName;

    this.subCrates = jsiiModule.submodules.map(
      (submodule) => {
        return new RustSubmodule(submodule, modulesPath);
      }
    );
  }

  public emit(code: CodeMaker): void {
    this.emitSubCrates(code);
  }

  private emitSubCrates(code: CodeMaker): void {
    for (const subCrate of this.subCrates) {
      subCrate.emit(code);
    }
  }
}

export class Crate extends RustModule {
  private readonly assembly: Assembly;

  constructor(assembly: Assembly) {
    const modulesPath = `${assembly.name}/src`;
    super(assembly, modulesPath);
    this.assembly = assembly;
  }

  public emit(code: CodeMaker): void {
    super.emit(code);

    this.emitToml(code);
    this.emitLib(code);
  }

  private emitToml(code: CodeMaker): void {
    code.openFile(`${this.moduleName}/Cargo.toml`);
    code.line(`[package]`);
    code.line(`name = "${this.moduleName}"`);
    code.line(`version = "${this.assembly.version}"`);
    code.line(`edition = "2024"`);

    if (this.assembly.dependencies.length > 0) {
      code.line('');
      code.line(`[dependencies]`);
      for (const dep of this.assembly.dependencies) {
        let depName = dep.assembly.name.replace(/[@/]/g, '-');
        depName = depName.replace(/^[^a-zA-Z]+/, '');

        code.line(`${depName} = { version = "${dep.version}", path = "../${depName}" }`);
      }
    }

    // Add features for sub-crates
    if (this.subCrates.length > 0) {
      code.line('');
      code.line(`[features]`);
      code.line(`default = [`);
      for (const subCrate of this.subCrates) {
        code.line(`    "${subCrate.moduleName}",`);
      }
      code.line(`]`);

      for (const subCrate of this.subCrates) {
        code.line(`"${subCrate.moduleName}" = []`);
      }
    }

    code.closeFile(`${this.moduleName}/Cargo.toml`);
  }

  private emitLib(code: CodeMaker): void {
    code.openFile(`${this.moduleName}/src/lib.rs`);
    code.line(`// This file is auto-generated by jsii-pacmak.`);
    code.line(`// Do not edit this file manually.`);

    for (const subCrate of this.subCrates) {
      code.line(`#[cfg(feature = "${subCrate.moduleName}")]`);
      code.line(`pub mod ${subCrate.moduleName};`);
    }

    code.closeFile(`${this.moduleName}/src/lib.rs`);
  }
}

export class RustSubmodule extends RustModule {
  private readonly submodulesPath: string;

  constructor(submodule: ModuleLike, modulesPath?: string) {
    super(submodule, modulesPath);
    const submodulesPath = submodule.fqn.split('.').slice(1).join('/').replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();
    this.submodulesPath = `${modulesPath ? modulesPath + '/' : ''}/${submodulesPath}`;
  }

  public emit(code: CodeMaker): void {
    super.emit(code);

    code.openFile(`${this.submodulesPath}.rs`);
    code.line(`// This file is auto-generated by jsii-pacmak.`);
    code.line(`// Do not edit this file manually.`);
    for (const subCrate of this.subCrates) {
      code.line(`pub mod ${subCrate.moduleName};`);
    }
    code.closeFile(`${this.submodulesPath}.rs`);
  }
}