//! Rust runtime for jsii
//!
//! This library provides the runtime support for Rust code generated by jsii-pacmak.
//! It handles communication with the jsii kernel via stdin/stdout protocol.

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::io::{BufRead, BufReader, Write};
use std::process::{Command, Stdio};
use std::sync::{Arc, Mutex, OnceLock};
use std::thread;
use std::sync::mpsc;
use thiserror::Error;

/// Errors that can occur during jsii runtime operations
#[derive(Error, Debug)]
pub enum JsiiError {
    #[error("Serialization error: {0}")]
    Serialization(#[from] serde_json::Error),
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Runtime error: {0}")]
    Runtime(String),
}

pub type Result<T> = std::result::Result<T, JsiiError>;

/// Handshake response from jsii runtime
#[derive(Debug, Deserialize)]
pub struct HandshakeResponse {
    pub hello: String,
}

/// Request to load a jsii assembly
#[derive(Debug, Serialize)]
pub struct LoadRequest {
    pub api: String,
    pub name: String,
    pub version: String,
    pub tarball: String,
}

#[derive(Debug, Deserialize)]
pub struct LoadResponse {
    pub assembly: String,
    pub types: f64,
}

/// Request to create a new object
#[derive(Debug, Serialize)]
pub struct CreateRequest {
    pub api: String,
    pub fqn: String,
    pub args: Vec<Value>,
    pub overrides: Vec<Value>,
    pub interfaces: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct Override {
    pub method: String,
}

/// Response from create request
#[derive(Debug, Deserialize)]
pub struct CreateResponse {
    #[serde(rename = "$jsii.byref")]
    pub objref: Value,
    #[serde(rename = "$jsii.interfaces", skip_serializing_if = "Option::is_none")]
    pub interfaces: Option<Vec<String>>,
}

/// Request to invoke a method
#[derive(Debug, Serialize)]
pub struct InvokeRequest {
    pub api: String,
    pub objref: Value,
    pub method: String,
    pub args: Vec<Value>,
}

/// Response from invoke request
#[derive(Debug, Deserialize)]
pub struct InvokeResponse {
    pub result: Value,
}

/// Request to get a property
#[derive(Debug, Serialize)]
pub struct GetRequest {
    pub api: String,
    pub objref: Value,
    pub property: String,
}

/// Response from get request
#[derive(Debug, Deserialize)]
pub struct GetResponse {
    pub value: Value,
}

/// Request to set a property
#[derive(Debug, Serialize)]
pub struct SetRequest {
    pub api: String,
    pub objref: Value,
    pub property: String,
    pub value: Value,
}

/// Jsii runtime client
pub struct JsiiClient {
    child: std::process::Child,
    reader: BufReader<std::process::ChildStdout>,
    writer: std::process::ChildStdin,
}

impl JsiiClient {
    /// Create a new jsii client and start the runtime process
    pub fn new() -> Result<Self> {
        println!("🚀 Starting jsii runtime process...");
        
        // Try different possible paths for the jsii runtime  
        let possible_paths = vec![
            "/home/clear/jsii/packages/@jsii/runtime/bin/jsii-runtime",
            "../../../../packages/@jsii/runtime/bin/jsii-runtime", // From rust-runtime-test/project
            "../../../runtime/bin/jsii-runtime", // From rust-runtime
            "packages/@jsii/runtime/bin/jsii-runtime", // From jsii root
            "node_modules/@jsii/runtime/bin/jsii-runtime",
        ];
        
        let mut child = None;
        for path in possible_paths {
            if let Ok(c) = Command::new("node")
                .arg(path)
                .stdin(Stdio::piped())
                .stdout(Stdio::piped())
                .stderr(Stdio::piped())
                .spawn()
            {
                println!("✅ Found jsii runtime at: {}", path);
                child = Some(c);
                break;
            }
        }
        
        let mut child = child.ok_or_else(|| {
            JsiiError::Runtime(
                "Could not find jsii runtime. Make sure the jsii runtime is available".to_string()
            )
        })?;

        let stdin = child.stdin.take().unwrap();
        let stdout = child.stdout.take().unwrap();
        let stderr = child.stderr.take().unwrap();

        // Handle stderr in a separate thread
        let (stderr_tx, stderr_rx) = mpsc::channel();
        thread::spawn(move || {
            let reader = BufReader::new(stderr);
            for line in reader.lines() {
                if let Ok(line) = line {
                    stderr_tx.send(line).ok();
                }
            }
        });

        // Monitor stderr
        thread::spawn(move || {
            while let Ok(line) = stderr_rx.recv() {
                eprintln!("JSII STDERR: {}", line);
            }
        });

        let reader = BufReader::new(stdout);
        let writer = stdin;

        Ok(JsiiClient {
            child,
            reader,
            writer,
        })
    }

    /// Initialize handshake with jsii runtime (synchronous)
    pub fn handshake(&mut self) -> Result<HandshakeResponse> {
        println!("📡 Reading handshake...");
        let mut handshake_line = String::new();
        self.reader.read_line(&mut handshake_line)?;
        println!("Received: {}", handshake_line.trim());
        
        let handshake: HandshakeResponse = serde_json::from_str(&handshake_line)?;
        println!("✅ Handshake successful: {}", handshake.hello);
        Ok(handshake)
    }

    /// Load a jsii assembly (synchronous)
    pub fn load(&mut self, name: String, version: String, tarball: String) -> Result<()> {
        println!("📦 Loading assembly: {} v{}", name, version);
        
        let request = LoadRequest {
            api: "load".to_string(),
            name,
            version,
            tarball,
        };

        let request_json = serde_json::to_string(&request)?;
        writeln!(self.writer, "{}", request_json)?;
        self.writer.flush()?;

        let mut response_line = String::new();
        self.reader.read_line(&mut response_line)?;
        
        let response: Value = serde_json::from_str(&response_line)?;
        if let Some(ok_value) = response.get("ok") {
            let load_response: LoadResponse = serde_json::from_value(ok_value.clone())?;
            println!("✅ Assembly loaded: {} with {} types", load_response.assembly, load_response.types);
            Ok(())
        } else {
            Err(JsiiError::Runtime(format!("Load failed: {}", response_line)))
        }
    }

    /// Create a new object (synchronous)
    pub fn create(
        &mut self,
        fqn: String,
        args: Vec<Value>,
        _overrides: Option<Vec<Override>>,
        _interfaces: Option<Vec<String>>,
    ) -> Result<CreateResponse> {
        println!("🔨 Creating object: {}", fqn);
        
        let request = CreateRequest {
            api: "create".to_string(),
            fqn,
            args,
            overrides: vec![],
            interfaces: vec![],
        };

        let request_json = serde_json::to_string(&request)?;
        println!("📤 Sending request: {}", request_json);
        writeln!(self.writer, "{}", request_json)?;
        self.writer.flush()?;

        let mut response_line = String::new();
        self.reader.read_line(&mut response_line)?;
        println!("📥 Raw response: {}", response_line.trim());
        
        let response: Value = serde_json::from_str(&response_line)?;
        if let Some(ok_value) = response.get("ok") {
            println!("📋 OK value: {}", ok_value);
            
            // Parse the create response - need to handle different response formats
            if let Some(byref_str) = ok_value.get("$jsii.byref").and_then(|v| v.as_str()) {
                // Direct byref string format
                println!("✅ Object created: {}", byref_str);
                Ok(CreateResponse {
                    objref: json!({"$jsii.byref": byref_str}),
                    interfaces: None,
                })
            } else {
                // Try to parse as full CreateResponse
                let create_response: CreateResponse = serde_json::from_value(ok_value.clone())?;
                println!("✅ Object created with full response");
                Ok(create_response)
            }
        } else {
            Err(JsiiError::Runtime(format!("Create failed: {}", response_line)))
        }
    }

    /// Invoke a method on an object (synchronous)
    pub fn invoke(
        &mut self,
        objref: Value,
        method: String,
        args: Vec<Value>,
    ) -> Result<InvokeResponse> {
        println!("⚡ Invoking method: {}", method);
        
        let request = InvokeRequest {
            api: "invoke".to_string(),
            objref,
            method,
            args,
        };

        let request_json = serde_json::to_string(&request)?;
        writeln!(self.writer, "{}", request_json)?;
        self.writer.flush()?;

        let mut response_line = String::new();
        self.reader.read_line(&mut response_line)?;
        
        let response: Value = serde_json::from_str(&response_line)?;
        if let Some(ok_value) = response.get("ok") {
            if let Some(result) = ok_value.get("result") {
                println!("✅ Method invoked successfully");
                Ok(InvokeResponse {
                    result: result.clone(),
                })
            } else {
                Ok(InvokeResponse {
                    result: Value::Null,
                })
            }
        } else {
            Err(JsiiError::Runtime(format!("Invoke failed: {}", response_line)))
        }
    }

    /// Get a property from an object (synchronous)
    pub fn get(&mut self, objref: Value, property: String) -> Result<GetResponse> {
        println!("📋 Getting property: {}", property);
        
        let request = GetRequest {
            api: "get".to_string(),
            objref,
            property,
        };

        let request_json = serde_json::to_string(&request)?;
        writeln!(self.writer, "{}", request_json)?;
        self.writer.flush()?;

        let mut response_line = String::new();
        self.reader.read_line(&mut response_line)?;
        
        let response: Value = serde_json::from_str(&response_line)?;
        if let Some(ok_value) = response.get("ok") {
            if let Some(value) = ok_value.get("value") {
                println!("✅ Property retrieved successfully");
                Ok(GetResponse {
                    value: value.clone(),
                })
            } else {
                Ok(GetResponse {
                    value: Value::Null,
                })
            }
        } else {
            Err(JsiiError::Runtime(format!("Get property failed: {}", response_line)))
        }
    }

    /// Set a property on an object (synchronous)
    pub fn set(&mut self, objref: Value, property: String, value: Value) -> Result<()> {
        println!("📝 Setting property: {} = {}", property, value);
        
        let request = SetRequest {
            api: "set".to_string(),
            objref,
            property,
            value,
        };

        let request_json = serde_json::to_string(&request)?;
        writeln!(self.writer, "{}", request_json)?;
        self.writer.flush()?;

        let mut response_line = String::new();
        self.reader.read_line(&mut response_line)?;
        
        let response: Value = serde_json::from_str(&response_line)?;
        if response.get("ok").is_some() {
            println!("✅ Property set successfully");
            Ok(())
        } else {
            Err(JsiiError::Runtime(format!("Set property failed: {}", response_line)))
        }
    }

    /// Shutdown the jsii runtime
    pub fn shutdown(&mut self) -> Result<()> {
        println!("🛑 Shutting down jsii runtime...");
        writeln!(self.writer, r#"{{"exit":0}}"#)?;
        self.writer.flush()?;
        let exit_status = self.child.wait()?;
        println!("✅ Runtime exited: {:?}", exit_status);
        Ok(())
    }
}

impl Default for JsiiClient {
    fn default() -> Self {
        Self::new().expect("Failed to create jsii client")
    }
}

/// Global jsii client instance (thread-safe singleton)
static GLOBAL_CLIENT: OnceLock<Arc<Mutex<JsiiClient>>> = OnceLock::new();

/// Initialize the global jsii client (completely thread-safe)
pub fn init() -> Result<()> {
    GLOBAL_CLIENT.get_or_try_init(|| {
        // This closure runs exactly once, even with multiple concurrent calls
        println!("🔧 Initializing global jsii client...");
        let mut client = JsiiClient::new()?;
        client.handshake()?;
        println!("✅ Global jsii client initialized");
        Ok(Arc::new(Mutex::new(client)))
    })?;
    
    Ok(())
}

/// Get a reference to the global jsii client (completely safe)
pub fn client() -> Result<Arc<Mutex<JsiiClient>>> {
    GLOBAL_CLIENT
        .get()
        .cloned()
        .ok_or_else(|| JsiiError::Runtime("Jsii client not initialized".to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_client_creation() {
        // This test might fail in CI environments without jsii-runtime
        if let Ok(mut client) = JsiiClient::new() {
            let response = client.handshake().unwrap();
            assert!(response.hello.contains("jsii-runtime"));
        }
    }
} 